name: Lint & Format
on: [push, pull_request]
jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/setup-uv@v1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: uv pip install --system flake8 black isort
      - run: |
          flake8 .
          isort --check-only .
          black --check .
