name: Test Suite
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/setup-uv@v1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: uv pip install --system -e .
      - run: uv pip install --system pytest flake8 black clipboard coverage pytest-cov pyyaml
      - run: black --check f2clipboard.py tests
      - run: flake8
      - run: pytest --cov=f2clipboard --cov=tests -q
      - run: coverage xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
