name: lint-and-test

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -U pip ruff pytest pytest-recording typer pydantic[dotenv]
      - run: ruff check .
      - run: pytest -q
